/*
상반기 아이스크림 총주문량이 3,000보다 높으면서 
아이스크림의 주 성분이 과일인 아이스크림의 맛을 
총주문량이 큰 순서대로 조회하는 SQL 문을 작성해주세요.
*/

/*
<첫 번째 답변>
SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF, ICECREAM_INFO
WHERE FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR AND TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;

JOIN ON 키워드 사용하는 습관 들이기.
그리고 긴 테이블 이름 alias 만들어서 사용하기.
*/

SELECT FH.FLAVOR
FROM FIRST_HALF FH JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
WHERE FH.TOTAL_ORDER > 3000 AND II.INGREDIENT_TYPE = 'FRUIT_BASED'
ORDER BY FH.TOTAL_ORDER DESC;

