/*
2022년 1월의 도서 판매 데이터를 기준으로 
저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여, 
저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 
리스트를 출력하는 SQL문을 작성해주세요.
결과는 저자 ID를 오름차순으로, 
저자 ID가 같다면 카테고리를 내림차순 정렬해주세요.
*/

/*
GROUP BY를 잘 사용하자.
*/

SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(BOOK.PRICE*BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK, AUTHOR, BOOK_SALES
WHERE BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID AND BOOK.BOOK_ID = BOOK_SALES.BOOK_ID AND TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY BOOK.AUTHOR_ID ASC, CATEGORY DESC;