/*
USED_GOODS_BOARD와 USED_GOODS_REPLY 테이블에서 
2022년 10월에 작성된 게시글 제목, 게시글 ID, 댓글 ID, 
댓글 작성자 ID, 댓글 내용, 댓글 작성일을 조회하는 SQL문을 작성해주세요. 
결과는 댓글 작성일을 기준으로 오름차순 정렬해주시고, 
댓글 작성일이 같다면 게시글 제목을 기준으로 오름차순 정렬해주세요.
*/

/*
이 문제에서 내가 몰랐던 것 : 기간을 지정하는 법

BETWEEN, AND는 알지만 나머지를 모름.

*/

-- 코드를 입력하세요
SELECT USED_GOODS_BOARD.TITLE, USED_GOODS_BOARD.BOARD_ID, USED_GOODS_REPLY.REPLY_ID, USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS, USED_GOODS_REPLY.CREATED_DATE
FROM USED_GOODS_BOARD, USED_GOODS_REPLY
WHERE USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID AND USED_GOODS_BOARD.CREATED_DATE
ORDER BY USED_GOODS_REPLY.CREATED_DATE ASC, USED_GOODS_BOARD.TITLE ASC;